server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/alechuertasfranco/ms-financiera
          search-paths: config-data
          username: alechuertasfranco
          password: wr6PtC7GrMbyXYA
  application:
    name: ms-config-server
