version: '3.3'
services:

  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_DATABASE: 'financiera'
      MYSQL_ROOT_PASSWORD: '12345'
    volumes:
      - './.mysql-data/financiera:/var/lib/mysql'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  ms-config-server:
    image: alechuertasf/ms-config-server
    container_name: ms-config-server
    ports:
      - '8888:8888'

  ms-eureka-server:
    image: alechuertasf/ms-eureka-server
    container_name: ms-eureka-server
    depends_on:
      - ms-config-server
    ports:
      - '8761:8761'

  ms-gateway:
    image: alechuertasf/ms-gateway
    container_name: ms-gateway
    depends_on:
      - ms-config-server
      - ms-eureka-server
    ports:
      - '8090:8090'

  ms-personas:
    image: alechuertasf/ms-personas
    container_name: ms-personas
    depends_on:
      - ms-config-server
      - ms-eureka-server
    ports:
      - '8001:8001'
      
  ms-solicitudes:
    image: alechuertasf/ms-solicitudes
    container_name: ms-solicitudes
    depends_on:
      - ms-config-server
      - ms-eureka-server
    ports:
      - '8002:8002'