version: '3.3'
services:

  database:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'financiera'      
      MYSQL_ROOT_PASSWORD: '12345'
    volumes:
      - './.mysql-data/financiera:/var/lib/mysql'
      
  ms-config-server:
    image: alechuertasf/ms-config-server
    container_name: ms-config-server
    ports:
      - '8888:8888'

        
  ms-eureka-server:
    image: alechuertasf/ms-eureka-server
    container_name: ms-eureka-server
    depends_on:
      - ms-config-server
    ports:
      - '8761:8761'