server:
  ports: 
    - "8761:8761"
spring:
  application:
    name: ms-solicitudes
eureka:
  instance:
    hostname: ms-eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/