server:
  port: 8761
spring:
  application:
    name: ms-solicitudes
eureka:
  instance:
    hostname: ms-eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/