
server:
  port: 8090
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-solicitudes
          uri: lb://ms-solicitudes
          predicates:
          - Path=/api/solicitudes/**
          filters: StripPrefix=2
        - id: ms-personas
          uri: lb://ms-personas
          predicates:
          - Path=/api/personas/**
          filters: StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders:
            - X-API-KEY
            - Origin
            - X-Requested-With
            - Content-Type
            - Accept
            - Access-Control-Request-Method
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - PUT
            - DELETE
  application:
    name: ms-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: ms-gateway