eureka:
  instance:
    hostname: ms-eureka-server
    prefer-ip-address: 'true'
    lease-renewal-interval-in-seconds: '10'
    lease-expiration-duration-in-seconds: '20'
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://4212-2800-200-f018-81d3-b9a4-3f4-9f35-2804.ngrok.io/eureka
spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  application:
    name: ms-personas
  datasource:
    password: '12345'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3300/financiera?
    #url: jdbc:mysql://0.tcp.ngrok.io:19069/financiera?
