eureka:
  instance:
    hostname: ms-eureka-server
    prefer-ip-address: 'true'
    lease-renewal-interval-in-seconds: '10'
    lease-expiration-duration-in-seconds: '20'
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://5f16-2800-200-f018-81d3-4187-665b-4f3e-8831.ngrok.io/eureka
spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  application:
    name: ms-solicitudes
  datasource:
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3307/financiera?
