spring:
  cloud:
    gateway:
      routes:
        - id: ms-solicitudes
          uri: lb://ms-solicitudes
          predicates:
          - Path=/api/solicitudes/**
          filters: StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders:
            - X-API-KEY
            - Origin
            - X-Requested-With
            - Content-Type
            - Accept
            - Access-Control-Request-Method
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - PUT
            - DELETE
  application:
    name: ms-gateway
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://4212-2800-200-f018-81d3-b9a4-3f4-9f35-2804.ngrok.io/eureka
server:
  port: '8090'